openapi: 3.0.0
info:
  title: Customer Management API
  description: API for managing customers and addresses
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /v1/address:
    post:
      summary: Create a new address
      description: Creates a new address for a customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddressRequest'
      responses:
        '201':
          description: Address created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddressDTO'
    put:
      summary: Update an existing address
      description: Updates an existing address by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddressRequest'
      responses:
        '200':
          description: Address updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddressDTO'
    delete:
      summary: Delete an address
      description: Deletes an address by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Address deleted successfully

components:
  schemas:
    AddressDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        state:
          type: string
        city:
          type: string
        district:
          type: string
        street:
          type: string
        number:
          type: string
        cep:
          type: string
        complement:
          type: string
        customerId:
          $ref: '#/components/schemas/CustomerDTO'

    AddressRequest:
      type: object
      properties:
        state:
          type: string
        city:
          type: string
        district:
          type: string
        street:
          type: string
        number:
          type: string
        cep:
          type: string
        complement:
          type: string
        customerId:
          type: integer
          format: int64

    CustomerDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
